name: Nightly

on:
  schedule:
    - cron: "8 0 * * *"

  workflow_dispatch:

jobs:
  auto_checks:
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Latest Memfault CLI
        run: |
          pip install --upgrade memfault-cli
          memfault --version

      - name: Verify Memfault CLI Help
        run: |
          printf '```text
          $ memfault --help
          %s
          ```
          ' "$(CI=1 memfault --help)" > help.txt

          diff -u src/pages/_partials/_memfault-cli-help.mdx help.txt

  run-if-failed:
    runs-on: ubuntu-latest
    needs: [auto_checks]

    # run if any job failed, only on the scheduled runs
    if: |
      always() && contains(needs.*.result, 'failure') && github.event_name == 'schedule'
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: failure
          SLACK_USERNAME: docs-nightly
          SLACK_ICON_EMOJI: ":boom:"
          MSG_MINIMAL: "actions url"
          SLACK_MESSAGE:
            "Auto checks failed for memfault/memfault-docs!"
